### ISSUE TITLE
trouble running picardmetrics on cygwin

### ISSUE THREAD

**Issue by gk-bioin4m8x** [slowkow/picardmetrics#6]
Hi @slowkow, 

I am trying to run the script on test files, but it shows following error:

`ERROR: Please install the 'stats' program`

stats is installed already, but I don't know why it shows this error.

Kindly guide.
Thanks!

**Comment by slowkow** [comment]
Please make sure that the `stats` program is in your `PATH`.

What happens when you execute:

```
which stats
```

or

```
echo $PATH
```

Is the `stats` program located inside one of the folders listed in `PATH`?

**Comment by gk-bioin4m8x** [comment]
It was not added, so I did  and now it shows the following with `echo $PATH` (which is the automatic selected location during installation):

`/home/name/src/filo/bin/stats`

But still its not working. I am using it on cygwin.

**Comment by gk-bioin4m8x** [comment]
@slowkow It was not added, so I did. With `echo $PATH' (automatic path selected during installation):

`/home/name/src/filo/bin/stats`

But still its not working and also missing in .conf file. I am using cygwin (Windows8.1, 64-bit).

**Comment by slowkow** [comment]
Could I ask you to please share your commands and output?

**Comment by gk-bioin4m8x** [comment]
@slowkow I am trying to use sample data by editing test.sh to script.sh:

```
#!/usr/bin/env bash
# adapted from test.sh
# Test picardmetrics on sample data
#
# data/project1/sample1.bam     10,000 paired-end 101 bp reads
# data/project1/sample2.bam     similar reads, but the header is shuffled

OK=1

main() {
  # Clean up previous runs.
  rm -rf out

  echo -e "$(DATE)\tSTART test_default"
  test_default
  echo -e "$(DATE)\tDONE test_default\n"

  if [[ ! $OK = 1 ]];then
    echo -e "$(DATE)\tFailed"
    exit 1
  fi
}

test_default() {
  out=out/samples_me
  mkdir -p $out

  run_log=$out/picardmetrics-run.log
  collate_log=$out/picardmetrics-collate.log
  rm -f $run_log $collate_log

  # Run multiple metrics on each BAM file.
  for f in data/project1/sample?/sample?.bam
  do
    ./picardmetrics run -f ~/picardmetrics.conf -o $out $f 2>&1 >> $run_log
  done

  # Collate the generated tables.
  ./picardmetrics collate $out $out &> $collate_log

  # Confirm that the final output is correct.
  checksum=$(md5sum ${out}-all-metrics.tsv | cut -f1 -d' ')
  if [[ ! "244cffd02775ab1517578147aee39ab1" = "$checksum" ]]; then
    cat $run_log >&2
    cat $collate_log >&2
    OK=0
  fi
}


DATE() {
  command date +'%Y-%m-%d %H:%M:%S'
}

main
```
#Output:
1) On screen:
>./script.sh

```
2017-06-02 16:46:31     START test_default
2017-06-02 16:46:31     picardmetrics config: '/home/NAME/picardmetrics.conf'
ERROR: Please install the 'stats' program
https://github.com/arq5x/filo
2017-06-02 16:46:32     picardmetrics config: '/home/NAME/picardmetrics.conf'
ERROR: Please install the 'stats' program
https://github.com/arq5x/filo
md5sum: out/samples_me-all-metrics.tsv: No such file or directory
picardmetrics version 0.2.4 2016-07-06
picardmetrics version 0.2.4 2016-07-06
picardmetrics version 0.2.4 2016-07-06
2017-06-02 16:46:32     START   out/samples_me
2017-06-02 16:46:32     Joining all files into 'out/samples_me-all-metrics.tsv'
Error in read_metrics(prefix) :
  Failed to read out/samples_me-alignment-metrics.tsv
Calls: main -> read_metrics
In addition: Warning message:
In read_tsv(sprintf("%s-alignment-metrics.tsv", prefix)) :
  File does not exist: out/samples_me-alignment-metrics.tsv
Execution halted
2017-06-02 16:46:32     DONE    out/samples_me
2017-06-02 16:46:32     DONE test_default

2017-06-02 16:46:32     Failed
```

2) /out/sample_me/picardmetrics-collate.txt

```
picardmetrics version 0.2.4 2016-07-06
2017-06-02 17:10:13	START	out/samples_me
2017-06-02 17:10:14	Joining all files into 'out/samples_me-all-metrics.tsv'
Error in read_metrics(prefix) : 
  Failed to read out/samples_me-alignment-metrics.tsv
Calls: main -> read_metrics
In addition: Warning message:
In read_tsv(sprintf("%s-alignment-metrics.tsv", prefix)) :
  File does not exist: out/samples_me-alignment-metrics.tsv
Execution halted
2017-06-02 17:10:14	DONE	out/samples_me
```

**Comment by slowkow** [comment]
Looks like [this code][1] is being triggered:

[1]: https://github.com/slowkow/picardmetrics/blob/master/picardmetrics#L364-L368

```bash
  if ! which stats &> /dev/null; then
    warn "ERROR: Please install the 'stats' program"
    warn "         https://github.com/arq5x/filo"
    exit 1
  fi
```

Please show the output of these commands:

```bash
which stats

which samtools

which java

echo $PATH

cat ~/picardmetrics.conf
```

**Comment by gk-bioin4m8x** [comment]
Yes, that's right.

```
which stats
no stats in (/usr/local/bin:/..................................)
```

I have also tried by installing filo inside bin, but stats did not work.

```
which samtools
/usr/local/bin/samtools
```

```
which java
/cygdrive/c/ProgramData/Oracle/Java/javapath/java
```
```
echo $PATH
Output is very large, but does not include stats
```

```
cat ~/picardmetrics.conf
# ~/picardmetrics.conf
# Change the values of these variables to match your system configuration.

# Write temporary files here.
TEMP_DIR=/tmp

# Run all jobs with niceness, to avoid interrupting interactive sessions.
NICENESS=20

# Picard Tools jar file.
PICARD_JAR="$HOME/src/picard-tools-1.126/picard.jar"

# Java invocation of Picard Tools.
PICARD="java -Xms5g -Xmx5g -jar $PICARD_JAR"

# Reference genome sequence.
REFERENCE_SEQUENCE="/PATH/TO/iGenomes.UCSC.hg19.genome.fa"

# Only for RNA-seq: annotations of all gene features.
REF_FLAT="/PATH/TO/gencode.v19.annotation.refFlat"

# Only for RNA-seq: all genomic intervals for ribosomal RNA genes.
RIBOSOMAL_INTERVALS="/PATH/TO/gencode.v19.annotation.rRNA.interval_list"

```

**Comment by slowkow** [comment]
1. Please copy the `stats` file into the folder `/usr/local/bin`.

    The `$PATH` environment variable is a listing of directories (folders). Your shell looks inside each folder to see if there is a file called `stats`. For example, when your shell looks inside `/usr/local/bin`, it finds the `samtools` file.

2. Please modify your `~/picardmetrics.conf` file to point to real files that exist on your system. For example, `/PATH/TO/gencode.v19.annotation.refFlat` does not exist on your system.

**Comment by gk-bioin4m8x** [comment]
@slowkow  Ok, thanks. 

Now I am getting another error while running `script.sh`:

```
CreateSequenceDictionary
ERROR: CreateSequenceDictionary failed. See: /home/NAME/bin/picardmetrics-master/out/samples_me_/iGenomes.UCSC.hg19.genome.fa.CreateSequenceDictionary.log
Error: Unable to access jarfile /home/name/src/picard-tools-1.126/picard.jar
```
I don't know why it shows this error, because I know picard.jar exists there and I have full access to the location.

In addition, when I run `java -Xms5g -Xmx5g -jar picard.jar` in another terminal window after cd picard-tools-1.126, it works fine and shows:
```
USAGE: PicardCommandLine <program name> [-h]
Available Programs:
```

**Comment by slowkow** [comment]
Ok, let's see what is inside this file:

```
/home/NAME/bin/picardmetrics-master/out/samples_me_/iGenomes.UCSC.hg19.genome.fa.CreateSequenceDictionary.log
```

**Comment by gk-bioin4m8x** [comment]
@slowkow Error: Unable to access jarfile /home/name/src/picard-tools-1.126/picard.jar

**Comment by gk-bioin4m8x** [comment]
@slowkow I hope if you can guide me regarding this error. :P

**Comment by slowkow** [comment]
If I understand you correctly, you're saying that this works:

```bash
cd /home/name/src/picard-tools-1.126
java -Xms5g -Xmx5g -jar picard.jar
```

And this does not work:

```bash
cd ~
java -Xms5g -Xmx5g -jar /home/name/src/picard-tools-1.126/picard.jar
```

Is that right?

**Comment by gk-bioin4m8x** [comment]
Yes, that's right.

**Comment by slowkow** [comment]
Please run the first example and the second example, and show the output. As mentioned before, it helps to see the commands you executed and the output.

One thing that caught my attention in your code is that you have 2 different paths:

```
/home/NAME
```

and lowercase `name`:

```
/home/name
```

Please make sure that you use the correct case (upper or lower) in the `picardmetrics.conf` file and in your commands.

Maybe you might want to check your folder permissions:

```bash
ls -lah /home
ls -lah /home/name
ls -lah /home/name/src
ls -lah /home/name/src/picard-tools-1.126
```

**Comment by gk-bioin4m8x** [comment]
@slowkow NAME is the username (for e.g. `NAME@computer`) and name is the folder name (`C:/cygwin64/home/name/bin/picardmetrics-master` and `C:/cygwin64/home/name/src/picard-tools-1.126/picard.jar`).
I am trying to run script on the example data only.
I checked the permissions, all are ok.

I am using name in all my codes, it is creating `iGenomes.UCSC.hg19.genome.fa.CreateSequenceDictionary.log` with the error (inside `/home/name/bin/picardmetrics-master/out/samples_me_/` but showing NAME on the screen).

```
2017-06-06 10:03:07     START test_default
2017-06-06 10:03:07     picardmetrics config: '/home/name/bin/picardmetrics-master/picardmetrics.conf'
2017-06-06 10:03:07     START   /home/name/bin/picardmetrics-master/data/project1/sample1/sample1.bam
2017-06-06 10:03:07     CreateSequenceDictionary
ERROR: CreateSequenceDictionary failed. See: /home/NAME/bin/picardmetrics-master/out/samples_me_/iGenomes.UCSC.hg19.genome.fa.CreateSequenceDictionary.log
Error: Unable to access jarfile /home/name/src/picard-tools-1.126/picard.jar
```

**Comment by gk-bioin4m8x** [comment]
As NAME is already saved in my Windows profile, which I cannot change, I renamed name to NAME to keep everything consistent, but still same error from CreateSequenceDictionary.

I think there is some issue with these two commands from .conf file while running in cygwin:

```
# Picard Tools jar file.
PICARD_JAR="/home/NAME/src/picard-tools-1.126/picard.jar"

# Java invocation of Picard Tools.
PICARD="java -Xms5g -Xmx5g -jar $PICARD_JAR"
```

**Comment by gk-bioin4m8x** [comment]
If I use the following in .conf:

```
# Picard Tools jar file.
PICARD_JAR=`cygpath -w /home/NAME/src/picard-tools-1.126/picard.jar`
```

Output is as follows:

```
2017-06-06 13:40:51     START test_default
2017-06-06 13:40:51     picardmetrics config: '/home/NAME/bin/picardmetrics-master/picardmetrics.conf'
2017-06-06 13:40:51     START   /home/NAME/bin/picardmetrics-master/data/project1/sample1/sample1.bam
2017-06-06 13:40:51     CreateSequenceDictionary
ERROR: CreateSequenceDictionary failed. See: /home/NAME/bin/picardmetrics-master/out/samples_me_/iGenomes.UCSC.hg19.genome.fa.CreateSequenceDictionary.log
[Tue Jun 06 13:40:51 CEST 2017] picard.sam.CreateSequenceDictionary REFERENCE=\home\NAME\bin\picardmetrics-master\data\iGenomes.UCSC.hg19.genome.fa OUTPUT=\home\NAME\bin\picardmetrics-master\data\iGenomes.UCSC.hg19.genome.dict TMP_DIR=[\home\NAME\tmp]    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Tue Jun 06 13:40:51 CEST 2017] Executing as NAME@computer on Windows 8.1 6.3 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Picard version: 1.126(4691ee611ac205d4afe2a1b7a2ea975a6f997426_1417447214) JdkDeflater
[Tue Jun 06 13:40:51 CEST 2017] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=5145362432
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Error opening file: iGenomes.UCSC.hg19.genome.fa
        at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:442)
        at htsjdk.samtools.reference.FastaSequenceFile.<init>(FastaSequenceFile.java:53)
        at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getReferenceSequenceFile(ReferenceSequenceFileFactory.java:81)
        at picard.sam.CreateSequenceDictionary.makeSequenceDictionary(CreateSequenceDictionary.java:137)
        at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:123)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)
Caused by: java.io.FileNotFoundException: \home\NAME\bin\picardmetrics-master\data\iGenomes.UCSC.hg19.genome.fa (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:438)
        ... 7 more
2017-06-06 13:40:52     ReorderSam
ERROR: ReorderSam failed. See: /home/NAME/bin/picardmetrics-master/out/samples_me_/sample1.ReorderSam.log
[Tue Jun 06 13:40:52 CEST 2017] picard.sam.ReorderSam INPUT=\home\NAME\tmp\picardmetrics_NAME_9456\home\NAME\bin\picardmetrics-master\data\project1\sample1\sample1.bam OUTPUT=\home\NAME\tmp\picardmetrics_NAME_9456\home\NAME\bin\picardmetrics-master\data\project1\sample1\sample1.ReorderSam.bam REFERENCE=\home\NAME\bin\picardmetrics-master\data\iGenomes.UCSC.hg19.genome.fa TMP_DIR=[\home\NAME\tmp\picardmetrics_NAME_9456\home\NAME\bin\picardmetrics-master\data\project1\sample1] VALIDATION_STRINGENCY=LENIENT    ALLOW_INCOMPLETE_DICT_CONCORDANCE=false ALLOW_CONTIG_LENGTH_DISCORDANCE=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Tue Jun 06 13:40:52 CEST 2017] Executing as NAME@computer on Windows 8.1 6.3 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Picard version: 1.126(4691ee611ac205d4afe2a1b7a2ea975a6f997426_1417447214) JdkDeflater
[Tue Jun 06 13:40:52 CEST 2017] picard.sam.ReorderSam done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=5145362432
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Cannot read non-existent file: C:\home\NAME\tmp\picardmetrics_NAME_9456\home\NAME\bin\picardmetrics-master\data\project1\sample1\sample1.bam
        at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:278)
        at picard.sam.ReorderSam.doWork(ReorderSam.java:93)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)
mv: cannot stat '/home/NAME/tmp/picardmetrics_NAME_9456//home/NAME/bin/picardmetrics-master/data/project1/sample1/sample1.ReorderSam.bam': No such file or directory
ERROR: Failed to move '/home/NAME/tmp/picardmetrics_NAME_9456//home/NAME/bin/picardmetrics-master/data/project1/sample1/sample1.ReorderSam.bam' to '/home/NAME/tmp/picardmetrics_NAME_9456//home/NAME/bin/picardmetrics-master/data/project1/sample1/sample1.bam'
2017-06-06 13:40:52     picardmetrics config: '/home/NAME/bin/picardmetrics-master/picardmetrics.conf'
2017-06-06 13:40:52     START   /home/NAME/bin/picardmetrics-master/data/project1/sample2/sample2.bam
2017-06-06 13:40:52     CreateSequenceDictionary
ERROR: CreateSequenceDictionary failed. See: /home/NAME/bin/picardmetrics-master/out/samples_me_/iGenomes.UCSC.hg19.genome.fa.CreateSequenceDictionary.log
[Tue Jun 06 13:40:52 CEST 2017] picard.sam.CreateSequenceDictionary REFERENCE=\home\NAME\bin\picardmetrics-master\data\iGenomes.UCSC.hg19.genome.fa OUTPUT=\home\NAME\bin\picardmetrics-master\data\iGenomes.UCSC.hg19.genome.dict TMP_DIR=[\home\NAME\tmp]    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Tue Jun 06 13:40:52 CEST 2017] Executing as NAME@computer on Windows 8.1 6.3 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Picard version: 1.126(4691ee611ac205d4afe2a1b7a2ea975a6f997426_1417447214) JdkDeflater
[Tue Jun 06 13:40:52 CEST 2017] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=5145362432
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Error opening file: iGenomes.UCSC.hg19.genome.fa
        at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:442)
        at htsjdk.samtools.reference.FastaSequenceFile.<init>(FastaSequenceFile.java:53)
        at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getReferenceSequenceFile(ReferenceSequenceFileFactory.java:81)
        at picard.sam.CreateSequenceDictionary.makeSequenceDictionary(CreateSequenceDictionary.java:137)
        at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:123)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)
Caused by: java.io.FileNotFoundException: \home\NAME\bin\picardmetrics-master\data\iGenomes.UCSC.hg19.genome.fa (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:438)
        ... 7 more
2017-06-06 13:40:53     ReorderSam
ERROR: ReorderSam failed. See: /home/NAME/bin/picardmetrics-master/out/samples_me_/sample2.ReorderSam.log
[Tue Jun 06 13:40:53 CEST 2017] picard.sam.ReorderSam INPUT=\home\NAME\tmp\picardmetrics_NAME_9928\home\NAME\bin\picardmetrics-master\data\project1\sample2\sample2.bam OUTPUT=\home\NAME\tmp\picardmetrics_NAME_9928\home\NAME\bin\picardmetrics-master\data\project1\sample2\sample2.ReorderSam.bam REFERENCE=\home\NAME\bin\picardmetrics-master\data\iGenomes.UCSC.hg19.genome.fa TMP_DIR=[\home\NAME\tmp\picardmetrics_NAME_9928\home\NAME\bin\picardmetrics-master\data\project1\sample2] VALIDATION_STRINGENCY=LENIENT    ALLOW_INCOMPLETE_DICT_CONCORDANCE=false ALLOW_CONTIG_LENGTH_DISCORDANCE=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Tue Jun 06 13:40:53 CEST 2017] Executing as NAME@computer on Windows 8.1 6.3 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Picard version: 1.126(4691ee611ac205d4afe2a1b7a2ea975a6f997426_1417447214) JdkDeflater
[Tue Jun 06 13:40:53 CEST 2017] picard.sam.ReorderSam done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=5145362432
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Cannot read non-existent file: C:\home\NAME\tmp\picardmetrics_NAME_9928\home\NAME\bin\picardmetrics-master\data\project1\sample2\sample2.bam
        at htsjdk.samtools.util.IOUtil.assertFileIsReadable(IOUtil.java:278)
        at picard.sam.ReorderSam.doWork(ReorderSam.java:93)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)
mv: cannot stat '/home/NAME/tmp/picardmetrics_NAME_9928//home/NAME/bin/picardmetrics-master/data/project1/sample2/sample2.ReorderSam.bam': No such file or directory
ERROR: Failed to move '/home/NAME/tmp/picardmetrics_NAME_9928//home/NAME/bin/picardmetrics-master/data/project1/sample2/sample2.ReorderSam.bam' to '/home/NAME/tmp/picardmetrics_NAME_9928//home/NAME/bin/picardmetrics-master/data/project1/sample2/sample2.bam'
md5sum: out/samples_me_-all-metrics.tsv: No such file or directory
picardmetrics version 0.2.4 2016-07-06
picardmetrics version 0.2.4 2016-07-06
picardmetrics version 0.2.4 2016-07-06
2017-06-06 13:40:53     START   out/samples_me_
2017-06-06 13:40:54     Joining all files into 'out/samples_me_-all-metrics.tsv'
Error in read_metrics(prefix) :
  Failed to read out/samples_me_-alignment-metrics.tsv
Calls: main -> read_metrics
In addition: Warning message:
In read_tsv(sprintf("%s-alignment-metrics.tsv", prefix)) :
  File does not exist: out/samples_me_-alignment-metrics.tsv
Execution halted
2017-06-06 13:40:54     DONE    out/samples_me_
2017-06-06 13:40:54     DONE test_default

2017-06-06 13:40:54     Failed
```

**Comment by slowkow** [comment]
You might want to try forward slashes (unix) instead of backward slashes
(windows).

Forward: /
Backward: \

Looks like it's important to get the paths correct.

**Comment by gk-bioin4m8x** [comment]
I have used / in .conf file, but I don't know why it is showing some places with \ in the output:

```
# Write temporary files here.
TEMP_DIR=/home/NAME/tmp

# Run all jobs with niceness, to avoid interrupting interactive sessions.
NICENESS=20

# Picard Tools jar file.
PICARD_JAR=`cygpath -w /home/NAME/src/picard-tools-1.126/picard.jar`

# Java invocation of Picard Tools.
PICARD="java -Xms5g -Xmx5g -jar $PICARD_JAR"

# Reference genome sequence.
REFERENCE_SEQUENCE="/home/NAME/bin/picardmetrics-master/data/iGenomes.UCSC.hg19.genome.fa"
```

**Comment by gk-bioin4m8x** [comment]
@slowkow As it has issues to run on cygwin, I ran it on linux server. It ran successfully and created default folder with text files and pdf for individual samples but did not generate following text files:
1) default-all-metrics  
2) default-base-distribution-by-cycle-histogram
3) default-gc-bias-histogram  
4) default-insert-size-histogram
5) default-library-complexity-histogram 
6) default-quality-histogram

Also, test_rnaseq failed.

How can I use picardmetrics for bam files already aligned to the reference?

**Comment by slowkow** [comment]
> How can I use picardmetrics for bam files already aligned to the reference?

The bam files provided in this repo are already aligned to the reference.

To learn more about bam files and how to work with them, please check out the GATK Forum Tutorials:
http://gatkforums.broadinstitute.org/gatk/categories/tutorials

> did not generate following text files

Thanks for reporting the missing files. Unfortunately, I can't help you because you haven't shared your commands and output. Please create a new issue for this.

Please consider reading this post that describes how to ask for help:

https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/

**The Golden Rule: Imagine You’re Trying To Answer The Question**

Finally, this issue will be closed and renamed to "trouble running picardmetrics on cygwin". Feel free to re-open it or post more information if you find out how to run on cygwin. Others might run into the same issue in the future.

**Comment by gk-bioin4m8x** [comment]
I have used the `test.sh `on the sample data and just edited path only in `.conf ` while running on linux server. I feel that manual needs to be more extensive.
Anyways, thank you for your help.
